name: Build Release Binaries

on:
  push
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target x86_64-unknown-linux-gnu

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target x86_64-pc-windows-msvc

  build-armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-musleabi
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target armv7-unknown-linux-musleabi
