name: Build and Release Binaries

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            command: build

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            command: build

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            command: build

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Rename binary 
        run: mv target/${{ matrix.platform.target }}/release/remote_switch_manager target/${{ matrix.platform.target }}/release/aarch64_remote_switch_manager
        if: matrix.platform.target == 'aarch64-unknown-linux-musl'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.platform.target }}/release/(aarch64_)?remote_switch_manager(\.exe)?
          fail_on_unmatched_files: false
          tag_name: "v${{ github.sha }}"
