name: Setup for Build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  setup-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ inputs.target }}
      - name: Install cross
        run: cargo install cross